/************************************************************************
* Palabra de honor:
* - No he discutido ni mostrado el código de mi programa con alguien que no sea mi *compañero,
Profesor o con el monitor asignado a este curso.
* 
* - No he utilizado código obtenido de otro u otros estudiantes,
* O cualquier otra fuente no autorizada, ya sea modificado o sin modificar.
*  Si cualquier código o documentación utilizada en mi programa
* Fue obtenido de otra fuente, tal como un libro de texto, notas del curso o Internet
* debe ser claramente señalado con una cita apropiada en
* los comentarios de mi programa.
*  Oscar Alberto Lozano Posso 0222120012
*  Juan Camilo Caro Rodriguez 0222121001
*************************************************************************/
package UI;

import java.awt.Dimension;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import logica.AgenciaDeViajes;
import logica.Vuelo;
import logica.OnlyNumbersDocumentFilter;

/**
 *
 * @author USUARIO
 */
public class Admin extends javax.swing.JFrame {
    AgenciaDeViajes agencia;//Se crrea una referencia a un objeto de la clase Agencia de Viajes
    public Admin() {
        agencia = new AgenciaDeViajes();//Se instancia el objeto
        setResizable(false);//Hacemos que la ventana no pueda ser redimensionada
        setMaximumSize(new Dimension(400, 500));//Asignamos su tamaño
        initComponents();
        
        AbstractDocument document3 = (AbstractDocument) txtPrecio.getDocument();
        document3.setDocumentFilter(new OnlyNumbersDocumentFilter());
        AbstractDocument document4 = (AbstractDocument) txtId.getDocument();
        document3.setDocumentFilter(new OnlyNumbersDocumentFilter());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon imagen = new ImageIcon("src/main/resources/Maracaibo.png");
        setIconImage(imagen.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreAerolinea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbDiaLlegada = new javax.swing.JComboBox<>();
        cmbMesLlegada = new javax.swing.JComboBox<>();
        cmbAñoLlegada = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbHoraSalida = new javax.swing.JComboBox<>();
        cmbHoraLlegada = new javax.swing.JComboBox<>();
        cmbTipoVuelo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbMinutos = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbMinutosLlegada = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel5.setText("Correo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button (10).png"))); // NOI18N
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnIngresar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 473, 550, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setPreferredSize(new java.awt.Dimension(50, 20));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 6, 93, -1));

        lblCedula.setText("ID:");
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, -1));

        jLabel2.setText("Origen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        txtOrigen.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 38, 93, -1));

        jLabel3.setText("Destino:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));

        txtDestino.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 70, 93, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(89, 137, 234));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha Salida");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, -1));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(89, 137, 234));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha LLegada");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 550, -1));

        jLabel7.setText("Tipo de Vuelo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel8.setText("NombreAerolinea:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 72, -1, -1));

        txtNombreAerolinea.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(txtNombreAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 70, 185, -1));

        jLabel9.setText("Precio:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        txtPrecio.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 108, 93, -1));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2023", "2024", "2025", "2026" }));
        jPanel1.add(cmbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        cmbDiaLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDiaLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaLlegadaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDiaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        cmbMesLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(cmbMesLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        cmbAñoLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2023", "2024", "2025", "2026" }));
        jPanel1.add(cmbAñoLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel10.setText("Año:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, 20));

        jLabel11.setText("Hora Llegada:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        cmbHoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "24" }));
        cmbHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoraSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        cmbHoraLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbHoraLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoraLlegadaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbHoraLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        cmbTipoVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Primera clase", "Business", "Economy", "Economica" }));
        cmbTipoVuelo.setPreferredSize(new java.awt.Dimension(50, 20));
        cmbTipoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVueloActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTipoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 38, 185, -1));

        jLabel12.setText("Minutos:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        cmbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinutosActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel13.setText("Minutos:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 20));

        cmbMinutosLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMinutosLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinutosLlegadaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMinutosLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "En tierra", "En vuelo", "Cancelado", "Retrasado" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(50, 20));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 6, 186, -1));

        jLabel1.setText("Estado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 8, -1, -1));

        jLabel17.setText("Hora Salida:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel18.setText("Día:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        jLabel19.setText("Mes:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 20));

        jLabel20.setText("Día:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel21.setText("Mes:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 20));

        jLabel22.setText("Año:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(89, 137, 234));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Administrador de Vuelos");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jMenu1.setText("Prueba");

        jMenuItem1.setText("Generar vuelos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Registro de informacion
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //PROXIMAMENTE: VALIDACION DE QUE NO HALLAN CAMPOS VACIOS-HECHO
        if((txtId.getText()!="") && (txtNombreAerolinea.getText() !="") && (txtOrigen.getText()!="") && (txtDestino.getText()!="") && (cmbTipoVuelo.getSelectedItem().toString()!=" ") && (cmbEstado.getSelectedItem().toString()!= " ") && (txtPrecio.getText()!="") && (cmbAño.getSelectedItem().toString()!=" ") && (cmbMes.getSelectedItem().toString()!=" ") && (cmbDia.getSelectedItem().toString()!=" ") && (cmbHoraSalida.getSelectedItem().toString()!=" ") && (cmbMinutos.getSelectedItem().toString()!=" ") && (cmbAñoLlegada.getSelectedItem().toString()!=" ") && (cmbMesLlegada.getSelectedItem().toString()!=" ") && (cmbDiaLlegada.getSelectedItem().toString()!=" ") && (cmbHoraLlegada.getSelectedItem().toString()!=" ") && (cmbMinutosLlegada.getSelectedItem().toString()!=" ") )
        {
          if(!agencia.buscarVuelo(Integer.parseInt(txtId.getText())))
          {
              //Se crea un objeto de tipo Vuelo
            Vuelo v1 = new Vuelo();
            //Se setean los atributos con los datos ingresados
            v1.setIdVuelo(Integer.parseInt(txtId.getText()));
            v1.setNombreAerolinea(txtNombreAerolinea.getText());
            v1.setOrigen(txtOrigen.getText());
            v1.setDestino(txtDestino.getText());
            v1.setTipoVuelo(cmbTipoVuelo.getSelectedItem().toString());
            v1.setEstado(cmbEstado.getSelectedItem().toString());
            //Se setea el precio
            v1.setPrecio(Double.parseDouble(txtPrecio.getText()));

            //creación de instancia de objeto de tipo Date
            Date fecha = new Date();
            Date fechaLlegada = new Date();
            //if(verificarFecha()){
            fecha.setYear(Integer.parseInt(cmbAño.getSelectedItem().toString()));
            fecha.setMonth(Integer.parseInt(cmbMes.getSelectedItem().toString()));
            fecha.setDate(Integer.parseInt(cmbDia.getSelectedItem().toString()));
            fecha.setHours(Integer.parseInt(cmbHoraSalida.getSelectedItem().toString()));
            fecha.setMinutes(Integer.parseInt(cmbMinutos.getSelectedItem().toString()));
            v1.setFechaSalida(fecha);//Se guarda la fecha de salida

            System.out.println((Integer.parseInt(cmbAñoLlegada.getSelectedItem().toString())));
            fechaLlegada.setYear(Integer.parseInt(cmbAñoLlegada.getSelectedItem().toString()));
            fechaLlegada.setMonth(Integer.parseInt(cmbMesLlegada.getSelectedItem().toString()));
            fechaLlegada.setDate(Integer.parseInt(cmbDiaLlegada.getSelectedItem().toString()));
            fechaLlegada.setHours(Integer.parseInt(cmbHoraLlegada.getSelectedItem().toString()));
            fechaLlegada.setMinutes(Integer.parseInt(cmbMinutosLlegada.getSelectedItem().toString()));
            //Se guarda la fecha de llegada
            v1.setFechaLlegada(fechaLlegada);
            agencia.leerVuelos();
            agencia.getVuelos().add(v1);
            
            if(agencia.añadirVuelos(agencia.getVuelos())){//Se añade el vuelo al ArrayList
                JOptionPane.showMessageDialog(null, "Se ha añadido un vuelo!");
                agencia.generadorDeVuelos();
            }
          }else
          {
              JOptionPane.showMessageDialog(null, "YA EXISTE UN VUELO REGISTRADO CON ESTE ID");
          }
        
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cmbHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHoraSalidaActionPerformed

    private void cmbHoraLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoraLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHoraLlegadaActionPerformed

    private void cmbMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMinutosActionPerformed

    private void cmbMinutosLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinutosLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMinutosLlegadaActionPerformed

    private void cmbDiaLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaLlegadaActionPerformed

    private void cmbTipoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVueloActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    agencia.generadorDeVuelos();
    JOptionPane.showMessageDialog(null, "SE HAN AGREGADO 50 VUELOS");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//Función para verificar que la fecha ingresada en los combobox sean válidas
    public boolean verificarFecha(){
        int dia = Integer.parseInt(cmbDia.getSelectedItem().toString());
        int mes = Integer.parseInt(cmbMes.getSelectedItem().toString());
        int anio = Integer.parseInt(cmbAño.getSelectedItem().toString());
        
        if(anio<1900 || anio > 2100){
            JOptionPane.showMessageDialog(null, "Año inválido","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    // Verificar que el día sea válido para el mes y año seleccionados
    if (mes == 2) {
        if (anio % 4 == 0 && (anio % 100 != 0 || anio % 400 == 0)) {
            if (dia < 1 || dia > 29) {
                JOptionPane.showMessageDialog(null, "Día inválido para febrero de año bisiesto", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            if (dia < 1 || dia > 28) {
                JOptionPane.showMessageDialog(null, "Día inválido para febrero de año no bisiesto", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
    } else if (mes == 4 || mes == 6 || mes == 9 || mes == 11) {
        if (dia < 1 || dia > 30) {
            JOptionPane.showMessageDialog(null, "Día inválido para el mes seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } else {
        if (dia < 1 || dia > 31) {
            JOptionPane.showMessageDialog(null, "Día inválido para el mes seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbAñoLlegada;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbDiaLlegada;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbHoraLlegada;
    private javax.swing.JComboBox<String> cmbHoraSalida;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbMesLlegada;
    private javax.swing.JComboBox<String> cmbMinutos;
    private javax.swing.JComboBox<String> cmbMinutosLlegada;
    private javax.swing.JComboBox<String> cmbTipoVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreAerolinea;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
